### ISSUE TITLE
Ability to limit cluster level permissions necessary to run mizu 

### ISSUE THREAD

**Issue by ksudhir007** [up9inc/mizu#122]
The minimum permissions needed to run mizu for the default cluster namespace are below:

```
- apiGroups:
  - ""
  - apps
  resources:
  - pods
  - services
  verbs:
  - list
  - get
  - create
  - delete
- apiGroups:
  - ""
  - apps
  resources:
  - daemonsets
  verbs:
  - list
  - get
  - create
  - patch
  - delete
```

However, when running in a shared cluster environments having these permissions on the default namespace is not possible for lot of reasons. It would be great if cluster level permissions are restricted to a specific namespace.

Happy to discuss more and contribute.
