### ISSUE TITLE
Couldn't find the kube config file, or file is empty

### ISSUE THREAD

**Issue by remover** [up9inc/mizu#857]
**Describe the bug**
Mizu claims it can't find the kube config file at the stated location but it's there.

**To Reproduce**
1. Run `mizu tap <pod-name>`
2. See error: "Couldn't find the kube config file, or file is empty (/path/to/.kube/config)"

**Expected behavior**
No error since the config file exists

**Logs**
There are no logs / zip file created when running the mizu command with `--set dump-logs=true`

**Desktop (please complete the following information):**
 - OS: macOS 11.6.4

**Additional context**

Here is the general structure of my config file:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: <server>
  name: ab
- cluster:
    server: <server>
  name: ac
- cluster:
    server: <server>
  name: ca
- cluster:
    server: <server>
  name: db
- cluster:
    server: <server>
  name: dt
- cluster:
    server: <server>
  name: et
contexts:
- context:
    cluster: ab
    user: iap
  name: ab
- context:
    cluster: ac
    user: iap
  name: ac
- context:
    cluster: ca
    user: iap
  name: ca
- context:
    cluster: db
    user: iap
  name: db
- context:
    cluster: dt
    user: iap
  name: dt
- context:
    cluster: et
    user: iap
  name: et
current-context: ""
kind: Config
preferences: {}
users:
- name: iap
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
...
```
